SECTION_BTNS = '.hh2c6'
COMMENT_BTN = '.hh2c6[aria-label*="評論"]'
AVG_RATING = '.fontDisplayLarge'
TOTAL_COUNT_CONTAINER = '.jANrlb'
SINGLE_CONTAINER = '.jftiEf'
AUTHOR = '.d4r55'
AUTHOR_DETAIL = '.RfnDt'
RATING = '.kvMYJc'
CONTENT = '.wiI7pd'
AUTHOR_LINK_A = '.al6Kxe'
WRITE_NEW_BTN = '.GMtm7c'
WRITE_NEW_CONTAINER = '.m6QErb.Hk4XGb.QoaCgb.XiKgde.KoSBEe.tLjsW'
READ_MORE_BTN = '.w8nwRe.kyuRq'
ITEM_BTNS = '.GBkF3d'
SCROLL_CONTAINER = '.m6QErb.DxyBCb.kA9KIf.dS8AEf.XiKgde[jslog="26354;mutable:true;"]'
TAG_CONTAINER = '.m6QErb.XiKgde.tLjsW .Zl7wsd .tXNTee'
TAG_COUNT = '.bC3Nkc.NlVald'
TAG_TXT = '.uEubGf.NlVald'
